### ISSUE TITLE
Mabye Rename rps project to Rock Papper scissor

### ISSUE THREAD

**Issue by AjayAntoIsDev** [FlyAbove/python.py#5]
rps is not a well known acronym  so its hard to understand what it means with actually looking into the folder

**Comment by FlyAbove** [comment]
### Thankyou @AjayAntoIsDev for opening an issue

You are right that rps isn't a popular acronym for rock, paper, scissors game but the reason I use rps as file name is to keep my folder's name as short as possible to give my files a cleaner look.
