### ISSUE TITLE
Add instructions/information in markdown files

### ISSUE THREAD

**Issue by ghost** [FlyAbove/python.py#6]
### Is your feature request related to a problem? Please describe.

I think the current way of teaching the material with python files and comments is good, but it could be more clear and detailed.more 

### Describe the solution you'd like

You could create multiple markdown files (basically writing an instruction manual or book about/for Python) that have the same information in the Python files' comments.

**Comment by FlyAbove** [comment]
## **Thankyou @eggnaut for opening an issue**

> I highly appreciate your feedback and recommendation, currently i am really occupied due to my college and studies, once i get enough time to work on this project again, I'll definitely keep your recommendation in mind and try to edit previous files and make them more detailed and work on the new files more accurately. 

> Sorry for getting back to you after such long time, your co-operation and patience is highly appreciated.

> For any new concerns, recommendations, questions or problems feel free to open new issue. 

>  **Happy coding! :)**

**Comment by eggnaut** [comment]
Thank you!

No worries, just an idea. :) Good luck with college!
